@startuml 状态图

[待机状态] --> [选择状态] : 原先没有选择图形，现在选择了一个
[选择状态] --> [更改状态] : 在这个选择的内部
[更改状态] --> [更改状态] : 可以多次更改
[更改状态] --> [待机状态] : 单机和矩形都没选择
[待机状态] --> [矩形选择状态] :当前没有选择
[矩形选择状态] --> [选择状态] : 这个矩形框内有形状
[创建形态] --> [选择状态]




@enduml